#Un módulo es simplemente un archivo .py con funciones, variables o clases que puedes usar en otros archivos.
#Es como una caja de herramientas que puedes importar y usar en cualquier parte de tu proyecto.
#♥
#✅ ¿Para qué sirven?
#♥
#Para organizar tu código en partes reutilizables
#♥
#Para no escribir lo mismo una y otra vez
#♥
#Para usar código de otras personas (como librerías: math, random, etc.)

#🧪 ¿Cómo funcionan los MÓDULOS INTERNOS de Python?
#Hay módulos que ya vienen con Python, como:

#math: funciones matemáticas
#random: cosas aleatorias
#datetime: fechas y horas
#os: sistema operativo
#sys: cosas del sistema de Python

#COMO SE IMPORTAN 

#import math
#print(math.sqrt(25))   √25 = 5