#'\n' → Para saltos de línea.

print("EJEMPLO DE SALTO DE LINEA\nLista de compras:\n- Manzanas\n- Pan\n-Leche")

#'\t' → Para tabulaciones.
print("\nEJEMPLO DE TABULACION")
print("Nombre:\tJuan")
print("Edad:\t25")
print("País:\tEspaña")

#'\\' → Para escribir barras invertidas.
print("\nEJEMPLO DE BARRA DOBLE")
ruta = "\nC:\\Users\\Juan\\Documentos"
print(ruta)

#'\"' → Para usar comillas dentro de strings.
print("\nEJEMPLO DE COMILLAS EN STRING")
print("Dijo: \"Python es genial!\"")

#'\uXXXX' → Para caracteres especiales (Unicode).
print("\nEJEMPLO DE CARACTERES ESPECIALES")
print("\u2764")  # Corazón ❤️
print("\U0001F600")  # Emoji 😀