#FORMA NO OPTIMA DE ABRIR UN ARCHIVO Y CERRARLO 

#PARA ABRIR EL ARCHIVO USAMOS OPEN
archivo = open("13.ARCHIVOS\\txt_csv\\texto.txt",encoding="utf-8")

#print(archivo.read())

#LEER ARCHIVOS POR LINEA
line = archivo.readline() #LEER PRIMERA LINEA
print(line)
#EL UNICOO PROBLEMA DE READLINE ES QUE EN ARCHIVOS GRANDES PUEDE CONSUMIR TODA LA MEMORIA DE LA COMPUTADORA
#PUEDE QUEDAR SIN RAM 
#POR LO QUE SOLO SE RECOMIENDA EN ARCHIVOS PEQUEÑOS SIN MUCHO TEXTO

#PARA CERRAR EL ARCHIVO USAMOS CLOSE

archivo.close() #ES IMPORTANTE CERRARLO PORQUE PUEDE CAUSAR COMPLICACIONES

#YA EL ARCHIVO SE CERRO Y SI QUEREMOS LEERLO DE VUELTA DEBEMOS USAR DE NUEVO LA FUNCION OPEN 
